[package]
name = "wizard"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14", features = ["image", "tokio"] }
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
uuid = { version = "1", features = ["v4"] }
indexmap = "2.12.1"
derive_more = { version = "2.1.1", features = ["deref", "deref_mut"] }
rand = "0.9.2"
strum = "0.27"
strum_macros = "0.27"

[features]
wiz_debug = []